const el=id=>document.getElementById(id);
async function status(){const {status}=await chrome.storage.local.get('status');el('status').textContent=status?`${status.ok?'CONNECTED':'CHECK REQUIRED'}\n${status.message}\n${status.at}`:'Not paired';}
chrome.storage.local.get('config').then(({config:c})=>{if(!c)return;el('token').value=c.token||'';el('league').value=c.leagueId||'';el('teams').value=JSON.stringify(c.teamMap||{},null,2);el('selector').value=c.rowSelector||'';el('myteam').value=c.myTeamId??'';el('season').value=c.season||2026;el('week').value=c.week||1;});
el('save').onclick=async()=>{try{const teamMap=JSON.parse(el('teams').value||'{}');if(!Object.values(teamMap).every(v=>Number.isInteger(v)&&v>=0))throw new Error('Team indexes must be nonnegative integers');await chrome.storage.local.set({config:{enabled:true,myTeamId:Number(el('myteam').value),season:Number(el('season').value),week:Number(el('week').value),token:el('token').value.trim(),leagueId:el('league').value.trim(),teamMap,rowSelector:el('selector').value.trim()||undefined}});el('status').textContent='Enabled. Open your paired ESPN draft room.';}catch(e){el('status').textContent=e.message;}};
el('stop').onclick=async()=>{const {config}=await chrome.storage.local.get('config');await chrome.storage.local.set({config:{...config,enabled:false}});el('status').textContent='Monitor paused';};
el('inspect').onclick=async()=>{try{const [tab]=await chrome.tabs.query({active:true,currentWindow:true});const result=await chrome.tabs.sendMessage(tab.id,{type:'inspect'});el('status').textContent=JSON.stringify(result,null,2);}catch(e){el('status').textContent=`Open an ESPN football page first. ${e.message}`;}};
status();

el('sync').onclick=async()=>{try{await el('save').onclick();el('status').textContent='Syncing ESPN league…';const result=await chrome.runtime.sendMessage({type:'sync-league'});el('status').textContent=result.message||result.error||JSON.stringify(result);}catch(e){el('status').textContent=e.message;}};
