import {_electron as electron} from '@playwright/test';
import path from 'node:path';
import fs from 'node:fs/promises';
const root=path.resolve('..');
const installed=process.env.FANTASY_TEST_EXE;
const instance=await electron.launch({executablePath:installed||path.join(root,'release','win-unpacked','Fantasy Manager.exe'),env:{...process.env,FANTASY_DISABLE_AUTO_REFRESH:'1',FANTASY_DATA_DIR:path.join(root,'storage','desktop-e2e')},timeout:90000});
try{
 const page=await instance.firstWindow({timeout:90000});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.getByRole('heading',{name:'Your weekly lineup'}).waitFor();
 const base=new URL(page.url()).origin;
 const b=await (await fetch(base+'/api/bootstrap')).json();
 if(b.version!=='0.4.1')throw new Error('Wrong frozen backend version');
 await page.getByRole('button',{name:'Connect my first team'}).waitFor();
 await page.getByRole('button',{name:'Manage ESPN',exact:true}).click();
 await page.getByRole('button',{name:'Open ESPN'}).waitFor();
 if(!await page.evaluate(()=>typeof window.fantasyDesktop?.connect==='function'))throw new Error('Desktop preload unavailable');
 await page.screenshot({path:path.join(root,'storage','desktop-home.png'),fullPage:true});
 const rate={wins:0,losses:0,pushes_or_ties:0,win_rate:null,decisions:0,ci95:null};
 const research={season:2026,week:1,updated_at:new Date().toISOString(),games:[{game_id:'fixture',home_team:'DEN',away_team:'KC',kickoff:'2026-09-13T20:25:00Z',state:'pre',completed:false,home_score:0,away_score:0,weather:{status:'forecast',temperature_f:75,wind_mph:9},forecast:{home_score:24.1,away_score:22.3,pick:'DEN',home_win_probability:.54,away_win_probability:.43,margin:1.8,total:46.4,market_home_margin:1,market_total:45,ats_pick:'home',total_pick:'over',reasons:['Synthetic UI fixture: personnel evidence'],components:{home:{baseline:22,factors:{home:2.1},offensive_replacements:0,opposing_defensive_replacements:0}}}}],accuracy:{straight_up:rate,against_spread:rate,totals:rate,score_mae:null,brier_score:null,games_graded:0,forecast_versions_saved:1,market_common_games:{model:rate,market_favorite:rate},results:[],players:{graded:0,mae:null,espn_mae:null,range_coverage:null}},sources:[],coverage_notes:['Synthetic UI test; no results graded.']};
 await page.route('**/api/intelligence',r=>r.fulfill({json:research}));
 await page.getByRole('button',{name:'NFL games',exact:true}).click();
 await page.getByRole('button',{name:'Refresh data & results',exact:true}).click();
 await page.getByText('Pick: DEN',{exact:true}).waitFor();
 await page.screenshot({path:path.join(root,'storage','desktop-games.png'),fullPage:true});
 await page.getByText('Pick: DEN',{exact:true}).click();
 await page.getByRole('heading',{name:'Market comparison',exact:true}).waitFor();
 await page.getByRole('button',{name:'Close',exact:true}).click();
 await page.getByRole('button',{name:'Accuracy',exact:true}).click();
 await page.getByRole('heading',{name:'Fantasy projection accuracy',exact:true}).waitFor();
 await page.screenshot({path:path.join(root,'storage','desktop-accuracy.png'),fullPage:true});
 await page.getByRole('button',{name:'Data & evidence',exact:true}).click();
 await page.getByRole('heading',{name:'Data availability',exact:true}).waitFor();
 if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+1))throw new Error('Page overflows window');
 await page.getByRole('button',{name:'Advanced tools',exact:true}).click();
 await page.getByRole('heading',{name:'Draft room',exact:true}).waitFor();
 await page.getByRole('button',{name:'My lineup',exact:true}).click();
 const p={id:'fixture-b',name:'Example healthy receiver',position:'WR',team:'DEMO',mean:14.2,p10:5.5,p90:25.6,boom:.19,bust:.2,injury_status:'ACTIVE',play_probability:1,locked:false,warnings:['Synthetic UI test'],injury:{},game:{opponent:'TEST'},usage:{targets:7.5}};
 await page.route('**/api/leagues/*/lineup',r=>r.fulfill({json:{starters:[{slot:'WR',player:p}],bench:[],projected_points:14.2,p10:5.5,p90:25.6,improvement:1.2,start:[p.name],sit:[],empty_slots:0,roster_updated:null,injury_source:{status:'fixture'},notes:['Synthetic test'],missing_projections:[]}}));
 await page.getByRole('button',{name:'Find my best lineup'}).click();
 await page.getByRole('heading',{name:'14.2 projected points'}).waitFor();
 await page.getByRole('button',{name:p.name,exact:true}).click();
 await page.getByRole('heading',{name:'Recent usage'}).waitFor();
 await page.getByRole('button',{name:'Close',exact:true}).click();
 if(errors.length)throw new Error(errors.join('\n'));
 await fs.writeFile(path.join(root,'storage','desktop-test.json'),JSON.stringify({passed:true,installed:!!installed,version:b.version,checks:['frozen backend starts','bundled UI loads','ESPN connection onboarding','sandboxed preload','advanced navigation','lineup rendering','player detail modal','NFL score cards and details','accuracy dashboard','source evidence'],consoleErrors:errors},null,2));
 console.log('Packaged desktop tests passed.');
}finally{await instance.close();}
