// Synthetic data for visual/interaction tests, never written into a user's ledger.
export function reviewFixture(){
 const metrics=[
  {key:'turnovers',team:'DEN',label:'Turnovers lost',unit:'turnovers',expected:1.1,low:0,high:2.4,actual:4,status:'surprise'},
  {key:'rushing_yards',team:'DEN',label:'Rushing yards',unit:'yards',expected:121,low:70,high:172,actual:138,status:'within_range'},
  {key:'net_passing_yards',team:'DEN',label:'Net passing yards',unit:'yards',expected:236,low:155,high:317,actual:162,status:'within_range'},
  {key:'epa_per_play',team:'DEN',label:'EPA per play',unit:'EPA/play',expected:.07,low:-.2,high:.34,actual:-.26,status:'surprise'},
  {key:'ngs_separation',team:'KC',label:'NGS receiver separation',unit:'yards',expected:3.2,low:2.5,high:3.9,actual:null,status:'awaiting_data'},
 ];
 const result={game_id:'review-fixture',home_team:'DEN',away_team:'KC',home_score:17,away_score:24,predicted_home:24.1,predicted_away:22.3,pick:'DEN',winner_result:'L',ats_result:'L',total_result:'L',saved_at:'2026-09-08T12:00:00Z',score_mae:4.4,margin_error:-8.8,total_error:-5.4,review_revisions:2,review:{observed_differences:['Synthetic UI fixture, not a real prediction.'],pre_game_factors:['Synthetic fixture: a starting defender was expected to miss the game.'],right:['Denver rushing production was within the saved reference range.','Two of four available statistical outcomes fell within their reference ranges.'],missed:['Winner: picked DEN; final winner KC.','DEN scored 17 versus 24.1 projected (−7.1).','DEN: turnovers and efficiency fell outside the saved reference ranges.'],unknown:['One Next Gen Stats metric is waiting for publication.'],comparisons:metrics,personnel:[{espn_id:'fixture-player',team:'DEN',name:'Example defender',position:'DB',status:'OUT',probability:0,likely:false,observed:null,matched:null}],conditions:[{label:'Kickoff wind',expected:9,actual:12,matched:true,source:'Synthetic weather observation'}],interpretation:'Measured differences do not establish causation. Synthetic test data; reference ranges are not calibrated probabilities.',learning_note:'This result will join the next candidate training set after its week closes and the correction window passes. It does not change the current pick retroactively.'}};
 const learning={phase:'shadow_testing',active:null,pending:'synthetic-candidate',eligible_games:80,validation_games:24,validation_weeks:2,minimum_training_games:80,minimum_test_games:32,minimum_test_weeks:3,correction_lag_days:4,max_adjustment:3,method:'The foundation refits completed game history on refresh. A frozen correction now shadows future games using saved statistical, weather and personnel expectations.',limits:'Synthetic test data. Promotion requires a future test; no edge over the market is established.',last_evaluation:null,events:[{kind:'candidate_started',created_at:'2026-09-08T12:00:00Z',artifact:'synthetic-candidate',training_games:80}]};
 const diagnostics={reliability:[{lower:.4,upper:.6,games:16,predicted:.54,actual:.5},{lower:.6,upper:.8,games:12,predicted:.68,actual:.66}],conditions:[{condition:'All games',games:28,score_mae:7.1,mean_total_error:1.2,record:{wins:16,losses:12,win_rate:16/28,ci95:[.38,.73]}},{condition:'Wind 15+ mph',games:4,score_mae:8.2,mean_total_error:-2,record:{wins:2,losses:2,win_rate:.5,ci95:[.15,.85]}}],market_margin:{games:28,model_mae:9.2,market_mae:8.8},market_total:{games:28,model_mae:11.3,market_mae:10.8},market_probability:{games:28,model_brier:.24,market_brier:.23},note:'Synthetic same-game comparisons; no real results are added to the live ledger.'};
 return {result,learning,diagnostics,expectations:{home:Object.fromEntries(metrics.filter(m=>m.team==='DEN').map(m=>[m.key,m]))}};
}
