import {useEffect,useRef,useState} from 'react';
import {Request,saveJson} from './Learning';

export type Metric={key?:string;team?:string;label:string;unit:string;expected:number;low:number;high:number;actual?:number|null;status?:string;error?:number|null;source?:{url?:string;fetched_at?:string;coverage?:string}};
type Personnel={espn_id:string;team:string;name:string;position?:string;status?:string;probability?:number;likely:boolean;observed:boolean|null;matched:boolean|null;snaps?:number|null};
export type GameResult={game_id:string;home_team:string;away_team:string;home_score:number;away_score:number;predicted_home:number;predicted_away:number;pick:string;winner_result:string;ats_result:string|null;total_result:string|null;saved_at:string;review_revisions?:number;score_mae?:number;margin_error?:number;total_error?:number;review:{observed_differences:string[];pre_game_factors:string[];interpretation:string;right?:string[];missed?:string[];unknown?:string[];comparisons?:Metric[];personnel?:Personnel[];conditions?:{label:string;expected:number;actual:number|null;matched:boolean|null;source:string}[];learning_note?:string}};
const n=(x:number|null|undefined)=>x==null?'—':x.toFixed(1);
function metric(x:number|null|undefined,unit:string){return x==null?'—':unit==='%'?`${(x*100).toFixed(1)}%`:unit==='EPA/play'?x.toFixed(2):unit==='pp'?`${n(x)} pp`:n(x);}

export function Expectations({values}:{values:Record<string,Record<string,Metric>>}){
 return <details className="expectation-details"><summary>Saved statistical expectations</summary><p>Offense and opponent-adjusted expectations. These are reference ranges, not calibrated confidence intervals.</p><div className="table-scroll"><table><thead><tr><th>Team</th><th>Statistic</th><th>Expected</th><th>Reference range</th></tr></thead><tbody>{Object.entries(values).flatMap(([side,rows])=>Object.entries(rows).map(([key,m])=><tr key={side+key}><td>{side}</td><td>{m.label}</td><td>{metric(m.expected,m.unit)}</td><td>{metric(m.low,m.unit)}–{metric(m.high,m.unit)}</td></tr>))}</tbody></table></div></details>;
}

export function GameReview({value,onClose,api}:{value:GameResult;onClose:()=>void;api:Request}){
 const [filter,setFilter]=useState('All'),[error,setError]=useState(''),[exporting,setExporting]=useState(false),close=useRef<HTMLButtonElement>(null),dialog=useRef<HTMLElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;close.current?.focus();function key(e:KeyboardEvent){if(e.key==='Escape')onClose();if(e.key==='Tab'){const els=dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],summary,[tabindex="0"]');if(!els?.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};},[]);
 const review=value.review,rows=review.comparisons??[];
 const selected=rows.filter(r=>filter==='All'||filter==='Surprises'&&r.status==='surprise'||filter==='Waiting for data'&&r.status==='awaiting_data');
 async function download(){setExporting(true);try{saveJson(await api(`/intelligence/games/${encodeURIComponent(value.game_id)}/audit`),`${value.game_id}-forecast-audit.json`);}catch(e){setError(String(e));}finally{setExporting(false);}}
 return <div className="modal-backdrop" onClick={onClose}><section ref={dialog} className="modal game-review" role="dialog" aria-modal="true" aria-labelledby="review-title" onClick={e=>e.stopPropagation()}><button ref={close} className="close" onClick={onClose}>Close</button><div className="eyebrow">POSTGAME REVIEW</div><h2 id="review-title">{value.away_team} at {value.home_team}</h2><p className="muted">Pick: {value.pick} · {value.winner_result==='W'?'Correct winner':value.winner_result==='T'?'Tie':'Missed winner'} · saved {new Date(value.saved_at).toLocaleString()}</p>
  <div className="review-scoreboard"><div><span></span><span>Projected</span><span>Final</span><span>Difference</span></div>{(['away','home'] as const).map(s=><div key={s}><strong>{value[s+'_team' as 'home_team'|'away_team']}</strong><b>{n(value[s==='home'?'predicted_home':'predicted_away'])}</b><b>{value[s==='home'?'home_score':'away_score']}</b><b>{n(value[s==='home'?'home_score':'away_score']-value[s==='home'?'predicted_home':'predicted_away'])}</b></div>)}</div>
  <div className="review-metrics"><span>Score error <b>{n(value.score_mae)} pts/team</b></span><span>Margin miss <b>{n(value.margin_error)} pts</b></span><span>Total miss <b>{n(value.total_error)} pts</b></span></div>
  <div className="learning-columns review-outcomes"><section><h3>What matched</h3>{review.right?.length?<ul>{review.right.map((v,i)=><li key={i}>{v}</li>)}</ul>:<p>No detailed pregame assumptions were saved with this older forecast.</p>}</section><section><h3>What missed</h3>{review.missed?.length?<ul>{review.missed.map((v,i)=><li key={i}>{v}</li>)}</ul>:<p>{rows.length?'No available outcomes exceeded the review thresholds.':'The detailed review starts with newly archived forecasts.'}</p>}</section></div>
  <h3>Expected vs. observed</h3><div className="review-filters">{['All','Surprises','Waiting for data'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div>
  {!!rows.length&&<div className="table-scroll"><table><thead><tr><th>Team / statistic</th><th>Expected</th><th>Reference range</th><th>Actual</th><th>Assessment</th></tr></thead><tbody>{selected.map((r,i)=><tr key={i}><td><strong>{r.team}</strong> · {r.label}{r.source?.url&&<small className="block"><a href={r.source.url} target="_blank" rel="noreferrer">Source</a>{r.source.fetched_at?` · ${new Date(r.source.fetched_at).toLocaleDateString()}`:''}</small>}</td><td>{metric(r.expected,r.unit)}</td><td>{metric(r.low,r.unit)}–{metric(r.high,r.unit)}</td><td>{metric(r.actual,r.unit)}</td><td><span className={`review-status ${r.status}`}>{r.status==='surprise'?'Outside range':r.status==='within_range'?'Within range':'Awaiting data'}</span></td></tr>)}</tbody></table>{!selected.length&&<p>No statistics in this category.</p>}</div>}
  {review.unknown?.map((text,i)=><p className="muted" key={i}>{text}</p>)}
  {!!review.personnel?.length&&<details><summary>Injury and participation assumptions</summary><p>Participation checks whether a player took part, not whether they completed the game or performed at full health.</p><div className="table-scroll"><table><thead><tr><th>Player</th><th>Pregame expectation</th><th>Observed</th></tr></thead><tbody>{review.personnel.map((p,i)=><tr key={i}><td>{p.team} · {p.name}<small className="block">{p.position} · {p.status}</small></td><td>{p.likely?'Likely playing':'Likely missing'}{p.probability==null?'':` · ${(p.probability*100).toFixed(0)}%`}</td><td>{p.observed==null?'Awaiting evidence':p.observed?'Participated':'No recorded snaps'}{p.snaps==null?'':` (${p.snaps} snaps)`}</td></tr>)}</tbody></table></div></details>}
  {!!review.conditions?.length&&<details><summary>Weather forecast vs. reported conditions</summary>{review.conditions.map((c,i)=><p key={i}>{c.label}: expected {n(c.expected)}, observed {n(c.actual)}{c.actual==null?' (not yet available)':''}.</p>)}</details>}
  <details><summary>What was known before kickoff</summary>{review.pre_game_factors.length?review.pre_game_factors.map((r,i)=><p key={i}>{r}</p>):<p>No verified personnel changes were applied.</p>}</details>
  <section className="review-learning"><h3>How this result is used</h3><p>{review.learning_note??'Final scores enter the accuracy record. Older forecasts without saved learning inputs cannot train the new correction model.'}</p><small>{review.interpretation}</small></section>
  <div className="benchmark-actions"><button disabled={exporting} onClick={()=>void download()}>{exporting?'Exporting…':'Export full prediction record'}</button><small>{value.review_revisions??1} saved review revision(s). Corrections preserve the original pick.</small></div>{error&&<p role="alert" className="error">{error}</p>}
 </section></div>;
}
