import {useRef,useState} from 'react';

export type Request=<T>(url:string,body?:unknown,method?:string)=>Promise<T>;
type Evaluation={games:number;weeks:number;champion_mae:number;candidate_mae:number;gain:number;gain_ci95:number[];champion_brier:number;candidate_brier:number;passed:boolean;rule:string;decision?:string;first_kickoff:string;last_kickoff:string};
export type LearningState={phase:string;active:string|null;pending:string|null;eligible_games:number;validation_games:number;validation_weeks:number;minimum_training_games:number;next_training_target?:number;minimum_test_games:number;minimum_test_weeks:number;correction_lag_days:number;max_adjustment:number;method:string;limits:string;last_evaluation:Evaluation|null;events:{kind:string;created_at:string;artifact:string;training_games?:number;comparison?:Evaluation}[]};
type Pair={games:number;model_mae:number|null;market_mae:number|null};
export type Diagnostics={reliability:{lower:number;upper:number;games:number;predicted:number;actual:number}[];conditions:{condition:string;games:number;score_mae:number;mean_total_error:number;record:{wins:number;losses:number;win_rate:number|null;ci95:number[]|null}}[];market_margin:Pair;market_total:Pair;market_probability:{games:number;model_brier:number|null;market_brier:number|null};note:string};
const n=(v:number|null|undefined,d=1)=>v==null?'—':v.toFixed(d);
const pct=(v:number|null|undefined)=>v==null?'—':`${(v*100).toFixed(1)}%`;

export function saveJson(value:unknown,name:string){
 const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));
 const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}

function EvaluationDetails({value}:{value:Evaluation}){
 return <><div className="learning-stats"><div><span>Current model error</span><strong>{n(value.champion_mae)} <small>pts/team</small></strong></div><div><span>Tested alternative error</span><strong>{n(value.candidate_mae)} <small>pts/team</small></strong></div><div><span>Improvement</span><strong>{n(value.gain)} <small>pts/team</small></strong></div></div><p>{value.games} future games across {value.weeks} NFL weeks. Improvement interval: {n(value.gain_ci95[0],2)} to {n(value.gain_ci95[1],2)} points. Probability error: {n(value.champion_brier,3)} → {n(value.candidate_brier,3)}.</p><small>{value.rule}</small></>;
}

export function Learning({value,diagnostics,graded}:{value?:LearningState;diagnostics?:Diagnostics;graded:number}){
 const phases:Record<string,string>={collecting:'Building the evidence',shadow_testing:'Testing a new correction',active:'A tested correction is active'};
 return <>
  <section className="card learning-intro"><div className="eyebrow">CONTINUOUS EVALUATION</div><h2>{phases[value?.phase??'collecting']}</h2><p>{value?.method??'Completed games update team history. New correction models are tested on future games before changing published picks.'}</p><div className="learning-steps">
   <div><span className="step-number">01</span><h3>Review</h3><strong>{graded} {graded===1?'game':'games'}</strong><p>Compare the saved pick, score and expectations with what happened.</p></div>
   <div><span className="step-number">02</span><h3>Learn</h3><strong>{value?.pending?`${value.eligible_games} eligible games`:`${value?.eligible_games??0} / ${value?.next_training_target??80} to train`}</strong><p>Fit a correction from completed weeks after a {value?.correction_lag_days??4}-day correction window.</p></div>
   <div><span className="step-number">03</span><h3>Test</h3><strong>{value?.pending?value.validation_games:0} / {value?.minimum_test_games??32} future games</strong><p>{value?.pending?value.validation_weeks:0} of {value?.minimum_test_weeks??3} required weeks. Shadow picks cannot change the published pick.</p></div>
   <div><span className="step-number">04</span><h3>Apply</h3><strong>{value?.active?'Validated correction':'Foundation model'}</strong><p>Promote only after the test passes. Cap the change at ±{value?.max_adjustment??3} points per team.</p></div>
  </div></section>
  <div className="learning-columns"><section className="card"><h3>What changes after a game</h3><p>Team scoring history and statistical expectations update on refresh. The review checks score errors, turnovers, efficiency, passing and rushing production, weather and expected participation.</p><p>Patterns in saved misses can produce a new correction. An individual upset does not automatically create a new rule.</p><small>Refresh runs when you open the app and every 15 minutes while it is running. Source publication delays still apply.</small></section><section className="card"><h3>What earns a change</h3><p>On later games, the candidate must improve score error by at least 0.15 points per team, with a positive lower bound on its 95% interval, and avoid a material increase in probability error.</p><p>Every candidate gets one test. Later fixed batches check active corrections against the original model and can roll them back.</p><small>{value?.limits}</small></section></div>
  {value?.last_evaluation&&<section className="card"><h3>Latest decision: {value.last_evaluation.decision?.replaceAll('_',' ')}</h3><EvaluationDetails value={value.last_evaluation}/></section>}
  <section className="card table-scroll"><h3>Learning history</h3>{value?.events.length?<table><thead><tr><th>When</th><th>Decision</th><th>Evidence</th><th>Model</th></tr></thead><tbody>{value.events.map((e,i)=><tr key={i}><td>{new Date(e.created_at).toLocaleDateString()}</td><td>{e.kind.replaceAll('_',' ')}</td><td>{e.comparison?`${e.comparison.games} later games · ${n(e.comparison.gain,2)} pts improvement`:`${e.training_games??0} training games`}</td><td><code>{e.artifact.slice(0,10)}</code></td></tr>)}</tbody></table>:<p>No correction has been trained or promoted yet. Your saved pregame picks build this record automatically.</p>}</section>
  <section className="card"><h3>Are the win probabilities trustworthy?</h3><p>If games average a 60% home-win prediction, the home team should win about 60% of them over a large sample.</p>{diagnostics?.reliability.length?<div className="table-scroll"><table><thead><tr><th>Predicted home-win band</th><th>Games</th><th>Average prediction</th><th>Actual home wins</th></tr></thead><tbody>{diagnostics.reliability.map(b=><tr key={b.lower}><td>{pct(b.lower)}–{pct(b.upper)}</td><td>{b.games}</td><td>{pct(b.predicted)}</td><td><div className="reliability-value"><span style={{width:`${b.actual*100}%`}}/><b>{pct(b.actual)}</b></div></td></tr>)}</tbody></table></div>:<p className="muted">Calibration appears after saved picks have final results.</p>}<small>Decisive games only; probabilities are conditional on no tie. Small samples are noisy.</small></section>
  <section className="card table-scroll"><h3>Where errors collect</h3>{diagnostics?.conditions.length?<table><thead><tr><th>Pregame condition</th><th>Games</th><th>Winner accuracy</th><th>Score error</th><th>Total bias</th></tr></thead><tbody>{diagnostics.conditions.map(c=><tr key={c.condition}><td>{c.condition}</td><td>{c.games}</td><td>{pct(c.record.win_rate)}</td><td>{n(c.score_mae)} pts</td><td>{c.mean_total_error>0?'+':''}{n(c.mean_total_error)} pts</td></tr>)}</tbody></table>:<p>Weather, injury and rest breakdowns appear as the live record grows.</p>}<small>A positive total bias means games scored more than predicted. Groups overlap and may differ in opponent strength; this table does not prove a condition caused the error.</small></section>
 </>;
}

export function MarketDiagnostics({value,external}:{value?:Diagnostics;external?:{source:string;games:number;model_mae:number;provider_mae:number}[]}){
 if(!value)return null;
 return <section className="card table-scroll"><h3>Score and probability benchmarks</h3><table><thead><tr><th>Same-game comparison</th><th>Games</th><th>Our error</th><th>Market error</th></tr></thead><tbody><tr><td>Winning margin</td><td>{value.market_margin.games}</td><td>{n(value.market_margin.model_mae)} pts</td><td>{n(value.market_margin.market_mae)} pts</td></tr><tr><td>Total points</td><td>{value.market_total.games}</td><td>{n(value.market_total.model_mae)} pts</td><td>{n(value.market_total.market_mae)} pts</td></tr><tr><td>Win probability (binary Brier)</td><td>{value.market_probability.games}</td><td>{n(value.market_probability.model_brier,3)}</td><td>{n(value.market_probability.market_brier,3)}</td></tr></tbody></table>{external?.map(row=><p key={row.source}>{row.source}: {row.games} common games · our score error {n(row.model_mae)} vs provider {n(row.provider_mae)} points per team.</p>)}<small>{value.note}</small></section>;
}

export function AddBenchmark({api,games,onRefresh}:{api:Request;games?:{game_id:string;home_team:string;away_team:string;state:string;kickoff:string}[];onRefresh:()=>void}){
 const file=useRef<HTMLInputElement>(null),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function upload(value:File){setBusy(true);setMessage('');setError('');try{if(value.size>128000)throw new Error('Use a JSON export smaller than 128 KB.');const result=await api<{imported:number;note:string}>('/intelligence/benchmarks',JSON.parse(await value.text()));setMessage(`${result.imported} comparisons imported. ${result.note}`);onRefresh();}catch(e){setError(String(e));}finally{setBusy(false);if(file.current)file.current.value='';}}
 const upcoming=games?.find(g=>g.state==='pre'&&new Date(g.kickoff)>new Date());
 return <section className="card"><h3>Add a forecast source</h3><p>Import a licensed game-score projection export to compare providers on the same games. Download the format, fill in the provider’s actual predictions and issue time, then import it before kickoff.</p><div className="benchmark-actions"><button disabled={!upcoming} onClick={()=>saveJson({source:'Replace with your licensed source',issued_at:new Date().toISOString(),rows:[{game_id:upcoming?.game_id,home_team:upcoming?.home_team,away_team:upcoming?.away_team,home_score:null,away_score:null,home_win_probability:null}]},'game-forecast-template.json')}>Download format</button><button disabled={busy} onClick={()=>file.current?.click()}>{busy?'Importing…':'Import forecast JSON'}</button><input ref={file} type="file" accept=".json,application/json" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);}}/></div>{message&&<p role="status">{message}</p>}{error&&<p role="alert" className="error">{error}</p>}<small>Game IDs and home/away teams must match NFL games. Imports are local benchmarks; they do not automatically change model weights or backfill old results. Existing player projection imports are in Advanced tools → Market / ADP.</small><p>Live multi-book odds can use a locally configured The Odds API key. Historical odds and licensed tracking data require provider access; the app does not claim those feeds are connected until they are available.</p></section>;
}
