import {useState} from 'react';
type Request=<T>(url:string,body?:unknown,method?:string)=>Promise<T>;
type Player={projection_change?:{delta:number;previous:number;injury_changed:boolean;context_changed:boolean};points_if_active?:number;participation_evidence?:{evidence:string[];method:string;calibrated:boolean};context?:{matchup?:{multiplier:number;defense_multiplier?:number;home_multiplier?:number;weather_multiplier?:number;personnel_multiplier?:number;evidence?:{games:number;raw_points_allowed:number}};play_calling?:{predicted_neutral_pass_rate?:number};advanced_usage?:Record<string,number>};id:string;name:string;position:string;team:string;mean:number;p10:number;p90:number;boom:number;bust:number;injury_status:string;play_probability:number;locked:boolean;warnings:string[];injury:{description?:string;source_url?:string};game:{opponent?:string};usage:Record<string,number>};
type Advice={estimated_win_probability?:number;matchup_assumptions?:string;starters:{slot:string;player:Player|null}[];bench:Player[];projected_points:number;p10:number;p90:number;improvement:number|null;start:string[];sit:string[];empty_slots:number;roster_updated:string;injury_source:{status:string;fetched_at:string};notes:string[];missing_projections:string[]};
export function Lineup({api,leagueId,onSync,beforeAnalyze}:{api:Request;leagueId:string;onSync?:()=>Promise<void>;beforeAnalyze?:(week:number)=>Promise<void>}){
 const [espnId,setEspnId]=useState(''),[team,setTeam]=useState(''),[season,setSeason]=useState(2026),[week,setWeek]=useState(1),[risk,setRisk]=useState('balanced');
 const [refreshRoster,setRefreshRoster]=useState(true);
 const [advice,setAdvice]=useState<Advice|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[detail,setDetail]=useState<Player|null>(null);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){setError(String(e));}finally{setBusy(false);}}
 const percent=(n:number)=>`${(n*100).toFixed(0)}%`;
 const playerRow=(p:Player,slot:string)=><tr key={p.id}><td>{slot}</td><td><button className="text-button" onClick={()=>setDetail(p)}>{p.name}</button><small> {p.position} · {p.team}{p.game.opponent?` vs ${p.game.opponent}`:''}</small></td><td><span className={['OUT','DOUBTFUL','QUESTIONABLE','INJURED_RESERVE'].includes(p.injury_status)?'status caution':'status'}>{p.injury_status.replaceAll('_',' ').toLowerCase()}</span><small>{percent(p.play_probability)} play chance</small>{p.locked?' · LOCKED':''}</td><td><b>{p.mean.toFixed(1)}</b></td><td>{p.p10.toFixed(1)}–{p.p90.toFixed(1)}</td><td>{percent(p.boom)}</td><td>{percent(p.bust)}</td></tr>;
 return <>{onSync&&<section className="card"><h3>Connect your ESPN leagues</h3><p>For public leagues, enter the league and team IDs from your ESPN URL. For private leagues, use “Sync league” in the paired Chrome extension while logged in. Both paths import all teams, roster slots, scoring rules and the selected week’s forecasts.</p><div className="toolbar"><label>ESPN league ID<input value={espnId} onChange={e=>setEspnId(e.target.value)} placeholder="leagueId from ESPN URL"/></label><label>Your ESPN team ID<input value={team} onChange={e=>setTeam(e.target.value)} placeholder="teamId from ESPN URL"/></label><label>Season<input type="number" value={season} onChange={e=>setSeason(+e.target.value)}/></label><button disabled={busy||!espnId||!team} onClick={()=>run(async()=>{await api('/espn/sync',{league_id:espnId,my_team_id:+team,season,week});await onSync?.();setMessage('League synced. Select it in the sidebar, then analyze its lineup.');})}>Sync public league</button></div>{message&&<p role="status">{message}</p>}</section>}
 <section className="card"><h3>Your best weekly lineup</h3><div className="toolbar"><label>Week<input aria-label="Lineup week" type="number" min="1" max="18" value={week} onChange={e=>{setWeek(+e.target.value);setAdvice(null);}}/></label><label>Objective<select value={risk} onChange={e=>{setRisk(e.target.value);setAdvice(null);}}><option value="balanced">Highest expected points</option><option value="floor">Favor floor</option><option value="upside">Favor upside</option><option value="win">Favor matchup win probability</option></select></label><button className="primary" disabled={busy} onClick={()=>run(async()=>{setAdvice(null);if(beforeAnalyze&&refreshRoster)await beforeAnalyze(week);setAdvice(await api(`/leagues/${leagueId}/lineup`,{week,risk,refresh_injuries:true}));})}>{busy?'Checking sources…':'Find my best lineup'}</button></div>{beforeAnalyze&&<label className="inline" style={{marginTop:16}}><input type="checkbox" checked={refreshRoster} onChange={e=>setRefreshRoster(e.target.checked)}/>Refresh ESPN roster first (turn off to use your last saved roster)</label>}{error&&<div className="alert error" role="alert">{error}</div>}</section>
 {advice&&<><section className="recommendation"><div className="eyebrow">RECOMMENDED STARTERS · {risk.toUpperCase()}</div><div className="hero-row"><div><h2>{advice.projected_points.toFixed(1)} projected points</h2><p>P10–P90 range: {advice.p10.toFixed(1)}–{advice.p90.toFixed(1)}</p></div><div className="ev"><strong>{advice.improvement===null?'—':`${advice.improvement>=0?'+':''}${advice.improvement.toFixed(1)}`}</strong><span>vs your synced current lineup</span></div></div><p>{advice.estimated_win_probability!=null&&<><b>{percent(advice.estimated_win_probability)} estimated matchup win chance</b><br/></>}{advice.start.length?`Start: ${advice.start.join(', ')}.`:'No new starters recommended.'} {advice.sit.length?`Sit: ${advice.sit.join(', ')}.`:''}</p>{advice.empty_slots>0&&<div className="warning">{advice.empty_slots} slots cannot be filled with available players. Check the injury list and missing projections.</div>}<small>Injury source: {advice.injury_source.status} · fetched {advice.injury_source.fetched_at??'unavailable'}<br/>Roster synced: {advice.roster_updated??'Not synced; draft/import ownership used'}</small></section>
 <section className="card table-scroll"><h3>Starting lineup</h3><table><thead><tr><th>Slot</th><th>Player</th><th>Status</th><th>Points</th><th>Likely range</th><th>Boom</th><th>Bust</th></tr></thead><tbody>{advice.starters.map((s,i)=>s.player?playerRow(s.player,s.slot):<tr key={`empty${i}`}><td>{s.slot}</td><td colSpan={6}>No eligible available player</td></tr>)}</tbody></table></section>
 <section className="card table-scroll"><h3>Bench comparisons</h3><table><thead><tr><th>Slot</th><th>Player</th><th>Status</th><th>Points</th><th>Likely range</th><th>Boom</th><th>Bust</th></tr></thead><tbody>{advice.bench.map(p=>playerRow(p,'BE'))}</tbody></table></section><details className="card"><summary>How these estimates are made</summary>{advice.matchup_assumptions&&<p>{advice.matchup_assumptions}</p>}{advice.notes.map(n=><p key={n}>{n}</p>)}{advice.missing_projections.length>0&&<p className="warning">Missing: {advice.missing_projections.join(', ')}</p>}</details></>}
 {detail&&<div className="modal-backdrop" onClick={()=>setDetail(null)}><section className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setDetail(null)}>Close</button><h2>{detail.name}</h2><p>{detail.injury_status} · {percent(detail.play_probability)} estimated chance to play</p><p><b>{detail.points_if_active?.toFixed(1)??detail.mean.toFixed(1)} points if active</b>. Participation probability is displayed separately and does not discount this forecast.</p>{detail.participation_evidence?.evidence.map((e,i)=><p key={i}>{e}</p>)}{detail.participation_evidence&&<small>Report-language estimate; not yet calibrated against enough historical outcomes.</small>}{detail.projection_change&&<p>Since the last saved forecast: {detail.projection_change.delta>=0?'+':''}{detail.projection_change.delta.toFixed(1)} points.{detail.projection_change.injury_changed?' Injury status changed.':''}{detail.projection_change.context_changed?' Matchup inputs changed.':''}</p>}{detail.context?.matchup&&<><h3 style={{marginTop:20}}>This week’s matchup</h3><p>Opponent adjustment: {(((detail.context.matchup.defense_multiplier??1)-1)*100).toFixed(1)}% · home/away: {(((detail.context.matchup.home_multiplier??1)-1)*100).toFixed(1)}% · weather: {(((detail.context.matchup.weather_multiplier??1)-1)*100).toFixed(1)}% · personnel: {(((detail.context.matchup.personnel_multiplier??1)-1)*100).toFixed(1)}%.</p><small>Applied to the independent forecast before blending with ESPN. Opponent effects account for offensive schedule strength.</small></>}{detail.context?.play_calling?.predicted_neutral_pass_rate!=null&&<p>Team’s modeled neutral-situation pass rate: {percent(detail.context.play_calling.predicted_neutral_pass_rate)}</p>}{detail.injury.description&&<p>{detail.injury.description}</p>}{detail.injury.source_url&&<a href={detail.injury.source_url} target="_blank" rel="noreferrer">Read injury source</a>}<h3>Recent usage</h3><div className="usage-grid">{Object.entries(detail.usage).map(([k,v])=><p key={k}><small>{k.replaceAll('_',' ')}</small><b>{typeof v==='number'?v.toFixed(1):String(v)}</b></p>)}</div>{detail.context?.advanced_usage&&<details><summary>Red-zone and play-by-play usage</summary>{Object.entries(detail.context.advanced_usage).map(([k,v])=><p key={k}>{k.replaceAll('_',' ')}: {v.toFixed(2)}</p>)}</details>}{detail.warnings.map(w=><p className="warning" key={w}>{w}</p>)}</section></div>}</>;
}
