import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';
import {Lineup} from './Lineup';
import {Home} from './Home';
type League={id:string;name:string;season:number;teams:number;my_team:number;slots:Record<string,number>;bench:number;mode:string;settings_verified:boolean;team_names:string[];draft_type:string;[key:string]:unknown};
type Pick={number:number;team:number;player_id:string};
type Player={id:string;name:string;position:string;team:string;mean:number;median:number;p10:number;p90:number;vorp:number;vonp?:number;gone?:number|null;bust:number;breakout:number;adp:number|null;tier:number;warnings:string[];independent:number;market:number|null;top3:number;top5:number;top12:number;expected_games:number;championship_probability?:number|null;championship_delta?:number|null;delta_ci95?:number[];next_targets?:{id:string;probability:number}[]};
type State={league:League;draft:{picks:Pick[];revision:number;updated:string|null;source:string|null};players:Player[];recommendations:Player[];warnings:string[];current_owner:number|null;catalog:{updated:string|null;revision:number}};
type Job={id:string;kind:string;status:string;error?:string;stale?:boolean;seconds?:number;result?:Record<string,unknown>&{results?:Partial<Player>[]}};
let token='';
async function api<T>(url:string,body?:unknown,method?:string):Promise<T>{const r=await fetch('/api'+url,{method:method??(body===undefined?'GET':'POST'),headers:{'Content-Type':'application/json','X-Local-Token':token},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(url==='/bootstrap'&&r.ok)token=data.token;if(!r.ok)throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data;}
const num=(v:number|undefined|null)=>v==null?'—':v.toFixed(1);
const pct=(v:number|undefined|null)=>v==null?'Unavailable':`${(v*100).toFixed(1)}%`;
function download(name:string,data:unknown){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click();URL.revokeObjectURL(a.href);}
function App(){
 const [leagues,setLeagues]=useState<League[]>([]),[id,setId]=useState(''),[state,setState]=useState<State|null>(null);
 const [tab,setTab]=useState('Draft room'),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [query,setQuery]=useState(''),[position,setPosition]=useState('ALL'),[settings,setSettings]=useState('');
 const [job,setJob]=useState<Job|null>(null),[deep,setDeep]=useState<Partial<Player>[]>([]),[result,setResult]=useState<unknown>(null);
 const [busy,setBusy]=useState(false),[auto,setAuto]=useState(false),[samples,setSamples]=useState(1000);
 const [week,setWeek]=useState(1),[risk,setRisk]=useState('balanced'),[faab,setFaab]=useState(100),[give,setGive]=useState(''),[receive,setReceive]=useState('');
 const [importKind,setImportKind]=useState('market'),[importText,setImportText]=useState(''),[showToken,setShowToken]=useState(false),[selected,setSelected]=useState<Player|null>(null);
 const replay=useRef<Pick[]>([]),autoRevision=useRef(''),activeId=useRef(id);activeId.current=id;
 async function load(){if(!id)return;const captured=id;const s=await api<State>(`/leagues/${id}/state`);if(activeId.current===captured)setState(s);}
 async function action(fn:()=>Promise<void>){setError('');setBusy(true);try{await fn();}catch(e){setError(String(e));}finally{setBusy(false);}}
 useEffect(()=>{api<{token:string;leagues:League[]}>('/bootstrap').then(b=>{token=b.token;setLeagues(b.leagues);setId(b.leagues[0]?.id??'');}).catch(e=>setError(String(e)));},[]);
 useEffect(()=>{setState(null);setDeep([]);setResult(null);setJob(null);autoRevision.current='';load().catch(e=>setError(String(e)));const t=setInterval(()=>load().catch(e=>setError(String(e))),2500);return()=>clearInterval(t);},[id]);
 useEffect(()=>{setDeep([]);},[state?.draft.revision,state?.catalog.revision]);
 useEffect(()=>{if(!job||!['running','queued'].includes(job.status))return;const captured=id;const t=setInterval(()=>api<Job>(`/jobs/${job.id}`).then(j=>{if(activeId.current!==captured)return;setJob(j);if(j.status==='error')setError(j.error??'Job failed');if(j.status==='complete'){if(j.stale){setNotice('Simulation superseded by a state change. Run again.');return;}if(j.kind==='draft')setDeep(j.result?.results??[]);else setResult(j.result);load().catch(e=>setError(String(e)));}}).catch(e=>setError(String(e))),1500);return()=>clearInterval(t);},[job?.id,job?.status,id]);
 useEffect(()=>{if(auto&&state&&state.current_owner===state.league.my_team&&!['running','queued'].includes(job?.status??'')){const key=`${id}:${state.draft.revision}:${state.catalog.revision}`;if(autoRevision.current!==key){autoRevision.current=key;runJob('simulate').catch(e=>setError(String(e)));}}},[auto,state?.draft.revision,state?.catalog.revision,job?.status]);
 async function runJob(kind:string){setDeep([]);setResult(null);setJob(await api<Job>(`/leagues/${id}/${kind}`,{simulations:samples,candidates:6,seed:42}));}
 async function record(p:Player){if(!state||state.current_owner===null)return;await api(`/leagues/${id}/draft?revision=${state.draft.revision}`,{picks:[...state.draft.picks,{number:state.draft.picks.length+1,team:state.current_owner,player_id:p.id}],source:'manual'});await load();}
 const playerMap=new Map(state?.players.map(p=>[p.id,p])),drafted=new Set(state?.draft.picks.map(p=>p.player_id));
 const recs=(state?.recommendations??[]).map(p=>({...p,...deep.find(r=>r.id===p.id)})).sort((a,b)=>deep.length?(b.championship_probability??-1)-(a.championship_probability??-1):0),top=recs[0];
 const teamName=(t:number)=>state?.league.team_names[t]||`Team ${t+1}`;
 const filtered=state?.players.filter(p=>!drafted.has(p.id)&&(position==='ALL'||p.position===position)&&`${p.name} ${p.team}`.toLowerCase().includes(query.toLowerCase()))??[];
 return <div className="shell"><aside><div className="brand"><span>FM</span> Fantasy Manager</div><div className="local">● LOCAL INTELLIGENCE</div><label>YOUR LEAGUE<select aria-label="League" value={id} onChange={e=>setId(e.target.value)}>{leagues.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><nav>{['My lineup','Draft room','Draft board','Player projections','Mock laboratory','Season management','Data & models','League settings'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>{setTab(t);if(t==='League settings'&&state)setSettings(JSON.stringify(state.league,null,2));}}>{t}</button>)}</nav><div className="sidebar-foot">Quantitative decisions.<br/>Manual execution in ESPN.<small>Model estimates require validation.</small></div></aside>
 <main><header><div><span className="eyebrow">{state?.league.season===2099?'ISOLATED SYNTHETIC DEMO':`${state?.league.season??2026} SEASON`} / {state?.league.mode??'DRAFT'}</span><h1>{tab}</h1></div><div className="header-meta"><span className="pill">{state?.league.teams??'—'} teams</span><span className="pill">{state?.draft.source??'Manual connection'}</span></div></header>
 {error&&<div className="alert error" role="alert">{error}<button onClick={()=>setError('')}>Dismiss</button></div>}{notice&&<div className="alert">{notice}<button onClick={()=>setNotice('')}>Dismiss</button></div>}{state?.warnings.map(w=><div className="warning" key={w}>{w}</div>)}{job&&<div className="job" role="status">{job.kind}: {job.status}{job.seconds!==undefined?` · ${job.seconds}s`:''}{job.stale?' · superseded':''}</div>}
 {!state?<p>Loading local engine…</p>:<>
 {tab==='My lineup'&&<Lineup key={id} api={api} leagueId={id} onSync={async()=>{setLeagues(await api('/leagues'));await load();}}/>}
 {tab==='Draft room'&&<><div className="toolbar"><span>Pick <b>{state.draft.picks.length+1}</b> · {state.current_owner===null?'Draft complete':teamName(state.current_owner)}{state.current_owner===state.league.my_team?' · YOUR TURN':''}</span><label className="inline"><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/>Auto-refine</label><button disabled={busy||state.current_owner!==state.league.my_team||['running','queued'].includes(job?.status??'')} onClick={()=>action(()=>runJob('simulate'))}>Simulate {samples.toLocaleString()} paths</button></div>
 {top?<section className="recommendation"><div className="eyebrow">{state.current_owner===state.league.my_team?"TOP RECOMMENDATION":"TOP RECOMMENDATION / PREVIEW"} · {deep.length?'SIMULATION REFINED':'FAST HEURISTIC'}</div><div className="hero-row"><div><span className={`position ${top.position}`}>{top.position}</span><h2>{top.name}</h2><span className="muted">{top.team} · Tier {top.tier}</span></div><div className="ev"><strong>{top.championship_delta==null?'Pending':`${top.championship_delta>=0?'+':''}${(top.championship_delta*100).toFixed(2)} pp`}</strong><span>Championship effect vs ADP policy</span>{top.delta_ci95&&<small>95% MC interval: {top.delta_ci95.map(v=>(v*100).toFixed(2)).join(' to ')} pp</small>}</div></div><div className="metrics">{[['Projected points',num(top.mean)],['VORP',num(top.vorp)],['Value over next pick',num(top.vonp)],['Gone before next pick',pct(top.gone)],['P10 / Median / P90',`${num(top.p10)} / ${num(top.median)} / ${num(top.p90)}`],['Bust / Breakout',`${pct(top.bust)} / ${pct(top.breakout)}`]].map(([k,v])=><div key={k}><small>{k}</small><strong>{v}</strong></div>)}</div><p className="explain">{top.name} offers {num(top.vorp)} points above this league’s starter replacement level. {top.gone==null?'Import ADP to estimate next-pick availability.':`The conditional ADP model estimates a ${pct(top.gone)} chance of being gone before your following pick.`} {deep.length?'Compare simulation intervals before treating small differences as meaningful.':'Interim ordering uses lineup gain, scarcity and opportunity cost; championship simulation is pending.'}</p><div className="hero-actions"><button className="primary" disabled={busy||state.current_owner!==state.league.my_team} onClick={()=>action(()=>record(top))}>Record my pick locally</button><span>Draft manually in ESPN, then record or let the monitor sync.</span></div></section>:<div className="empty">{state.players.length?'No legal picks remain.':'No projections loaded. Open Data & models.'}</div>}
 <section className="card"><h3>Best alternatives</h3><table><thead><tr><th>Player</th><th>Points</th><th>VORP</th><th>Gone</th><th>Championship effect</th><th></th></tr></thead><tbody>{recs.slice(1,6).map(p=><tr key={p.id}><td><span className={`position ${p.position}`}>{p.position}</span><button className="text-button" onClick={()=>setSelected(p)}>{p.name}</button></td><td>{num(p.mean)}</td><td>{num(p.vorp)}</td><td>{pct(p.gone)}</td><td>{p.championship_delta==null?'Pending':`${(p.championship_delta*100).toFixed(2)} pp`}</td><td><button disabled={busy} onClick={()=>action(()=>record(p))}>Record</button></td></tr>)}</tbody></table></section>
 <div className="two-col"><section className="card"><h3>Positional strategy</h3><p className="strategy">{Array.from(new Set(recs.map(r=>r.position))).join(' → ')||'Awaiting projections'}</p><small>Derived from current candidate order; changes every pick.</small></section><section className="card"><h3>Next-pick plan</h3>{top?.next_targets?.length?top.next_targets.map(t=><p key={t.id}>If available: <b>{playerMap.get(t.id)?.name??t.id}</b> · {pct(t.probability)} of paths</p>):<p>Run a candidate simulation to inspect likely follow-up selections.</p>}</section></div><section className="card"><h3>Record any pick</h3><input aria-label="Search available players" placeholder="Find a drafted player…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="search-results">{filtered.slice(0,10).map(p=><button key={p.id} disabled={busy} onClick={()=>action(()=>record(p))}>{p.name} <small>{p.position}</small></button>)}</div></section></>}
 {tab==='Draft board'&&<><div className="toolbar"><button onClick={()=>action(async()=>download(`${id}-replay.json`,await api(`/leagues/${id}/export`)))}>Export replay</button><label className="file-label">Load replay<input type="file" accept=".json" onChange={e=>{const f=e.target.files?.[0];action(async()=>{if(!f)return;const data=JSON.parse(await f.text());replay.current=data.draft?.picks??data.picks;setNotice(`Loaded ${replay.current.length} picks. Reset local draft to replay from the beginning.`);});}}/></label><button onClick={()=>action(async()=>{const next=replay.current.slice(0,state.draft.picks.length+1);if(next.length<=state.draft.picks.length)throw new Error('No remaining replay picks');await api(`/leagues/${id}/draft?revision=${state.draft.revision}`,{picks:next,source:'replay'});await load();})}>Replay next pick</button><button className="danger" onClick={()=>{if(window.confirm('Clear this local draft? ESPN is unaffected.'))action(async()=>{await api(`/leagues/${id}/reset?revision=${state.draft.revision}`,{picks:[],source:'manual'});await load();});}}>Reset local draft</button></div><div className="board-scroll"><div className="board" style={{gridTemplateColumns:`repeat(${state.league.teams},minmax(130px,1fr))`}}>{Array.from({length:state.league.teams},(_,t)=><div className={`team-head ${t===state.league.my_team?'mine':''}`} key={t}>{teamName(t)}</div>)}{Array.from({length:Object.values(state.league.slots).reduce((a,b)=>a+b,0)+state.league.bench},(_,round)=>Array.from({length:state.league.teams},(_,team)=>{const pick=state.draft.picks.find(p=>p.team===team&&Math.floor((p.number-1)/state.league.teams)===round),player=pick?playerMap.get(pick.player_id):null;return <div className={`pick ${player?.position??''}`} key={`${round}-${team}`}><small>ROUND {round+1}{pick?` · #${pick.number}`:''}</small><b>{player?.name??'—'}</b><span>{player?.position} {player?.team}</span></div>;}))}</div></div></>}
 {tab==='Player projections'&&<section className="card"><div className="toolbar"><input placeholder="Search players" aria-label="Search projections" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Position" value={position} onChange={e=>setPosition(e.target.value)}>{['ALL','QB','RB','WR','TE','K','DST'].map(p=><option key={p}>{p}</option>)}</select><span>{filtered.length} available</span></div><div className="table-scroll"><table><thead><tr><th>Player</th><th>Independent</th><th>Market</th><th>Ensemble</th><th>P10</th><th>P90</th><th>VORP</th><th>ADP</th><th>Tier</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><span className={`position ${p.position}`}>{p.position}</span><button className="text-button" onClick={()=>setSelected(p)}>{p.name}</button><small> {p.team}</small></td><td>{num(p.independent)}</td><td>{num(p.market)}</td><td>{num(p.mean)}</td><td>{num(p.p10)}</td><td>{num(p.p90)}</td><td>{num(p.vorp)}</td><td>{num(p.adp)}</td><td>{p.tier}</td></tr>)}</tbody></table></div></section>}
 {tab==='Mock laboratory'&&<><section className="card"><h3>Explore paths from your draft slot</h3><p>Uses probabilistic managers, legal rosters and weekly season simulations. Opening frequencies describe the sampled policy; they are not proof of an optimal strategy.</p><div className="toolbar"><label>Simulations<input type="number" min="64" max="10000" value={samples} onChange={e=>setSamples(Number(e.target.value))}/></label><button className="primary" disabled={['running','queued'].includes(job?.status??'')} onClick={()=>action(()=>runJob('mock'))}>Run mock drafts</button></div></section>{result!=null&&<Result value={result}/>}</>}
 {tab==='Season management'&&<><section className="card"><h3>Weekly lineup & free agents</h3><div className="toolbar"><label>Week<input type="number" min="1" max="18" value={week} onChange={e=>setWeek(Number(e.target.value))}/></label><label>Risk<select value={risk} onChange={e=>setRisk(e.target.value)}><option value="balanced">Balanced</option><option value="floor">Favor floor</option><option value="upside">Favor upside</option></select></label><label>FAAB remaining<input type="number" min="0" value={faab} onChange={e=>setFaab(Number(e.target.value))}/></label><button onClick={()=>action(async()=>setResult(await api(`/leagues/${id}/season`,{week,risk,faab_remaining:faab,overrides:{}})))}>Analyze week</button></div><p>Update local ownership after transactions. Weekly overrides are supported through the API.</p></section><section className="card"><h3>Trade evaluator</h3><div className="two-col"><label>Give: canonical IDs, comma separated<input value={give} onChange={e=>setGive(e.target.value)}/></label><label>Receive: canonical IDs, comma separated<input value={receive} onChange={e=>setReceive(e.target.value)}/></label></div><button onClick={()=>action(async()=>setResult(await api(`/leagues/${id}/trade`,{give:give.split(',').map(s=>s.trim()).filter(Boolean),receive:receive.split(',').map(s=>s.trim()).filter(Boolean),week})))}>Evaluate trade</button></section>{result!=null&&<Result value={result}/>}</>}
 {tab==='Data & models'&&<><section className="card"><h3>Source health & projections</h3><p>Last catalog update: {state.catalog.updated??'Never'}. Cached data include source URLs, retrieval times and hashes. Real 2026 data are isolated from the demo.</p><div className="toolbar"><button onClick={()=>action(async()=>setJob(await api('/refresh/2026',{})))}>Refresh 2026 nflverse data</button><button onClick={()=>action(async()=>setResult(await api('/sources')))}>Inspect sources</button><button onClick={()=>action(async()=>setJob(await api(`/leagues/${id}/backtest`,{})))}>Run rolling backtest</button></div></section><section className="card"><h3>Import source-backed data</h3><p>Paste market projections, player records or structured news as JSON. Use canonical IDs and underlying projected statistics, so scoring remains league-specific. See README and /docs for schemas.</p><select aria-label="Import type" value={importKind} onChange={e=>setImportKind(e.target.value)}><option value="market">Market / ADP</option><option value="players">Players / IDs / K / DST</option><option value="events">Structured event</option><option value="rosters">Current team rosters</option></select><textarea aria-label="Import JSON" value={importText} onChange={e=>setImportText(e.target.value)}/><button onClick={()=>action(async()=>{setResult(await api(importKind==='events'?'/events':importKind==='rosters'?`/leagues/${id}/rosters`:`/${importKind}/${state.league.season}`,JSON.parse(importText),importKind==='rosters'?'PUT':undefined));await load();})}>Validate & import</button></section><section className="card"><h3>Pair the ESPN monitor</h3><p>Load the unpacked extension in Chrome. Paste this token and league ID into its popup. ESPN credentials stay in Chrome.</p><button onClick={()=>setShowToken(!showToken)}>{showToken?'Hide':'Show'} pairing token</button>{showToken&&<code className="token">{token}</code>}<p>League ID: <code>{id}</code>. Verify DOM compatibility in your actual draft room before relying on it.</p></section>{result!=null&&<Result value={result}/>}</>}
 {tab==='League settings'&&<section className="card"><h3>Exact league configuration</h3><p>Edit scoring, weekly bonuses, FLEX rules, draft order, playoffs and waivers. Team indexes are zero-based. A new ID creates another league. Set settings_verified true only after checking ESPN.</p><button onClick={()=>setSettings(JSON.stringify({...state.league,id:`league-${Date.now()}`,name:'My ESPN league',season:2026,source:'manual',settings_verified:false},null,2))}>New league from these settings</button><textarea className="settings" aria-label="League settings JSON" value={settings} onChange={e=>setSettings(e.target.value)}/><button className="primary" onClick={()=>action(async()=>{const data=JSON.parse(settings) as League;await api(`/leagues/${data.id}`,data,'PUT');setLeagues(await api('/leagues'));setId(data.id);setNotice('League configuration saved.');await load();})}>Validate & save</button></section>}
 </>}<footer>Local-first · Manual ESPN picks · Championship estimates depend on uncalibrated assumptions</footer></main>
 {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>Close</button><span className={`position ${selected.position}`}>{selected.position}</span><h2>{selected.name}</h2><p>{selected.team} · ID <code>{selected.id}</code></p><p>Expected games {num(selected.expected_games)} · Top 3 {pct(selected.top3)} · Top 5 {pct(selected.top5)} · Top 12 {pct(selected.top12)}</p><p>P10 {num(selected.p10)} · Median {num(selected.median)} · P90 {num(selected.p90)}</p>{selected.warnings.map((w,i)=><p className="warning" key={i}>{w}</p>)}</section></div>}</div>;
}
function Result({value}:{value:unknown}){return <section className="card"><div className="toolbar"><h3>Analysis result</h3><button onClick={()=>download('fantasy-analysis.json',value)}>Export JSON</button></div><pre>{JSON.stringify(value,null,2)}</pre></section>;}
function Root(){const [advanced,setAdvanced]=useState(false);return advanced?<><button className="back-home" onClick={()=>setAdvanced(false)}>← Back to my teams</button><App/></>:<Home api={api} onAdvanced={()=>setAdvanced(true)}/>;}
createRoot(document.getElementById('root')!).render(<Root/>);

import './professional.css';
